# Working with Oversampler

## Importing required Libraries

In [2]:
import pandas as pd
from imblearn.over_sampling import RandomOverSampler
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

## Reading the CSV

In [3]:
data = pd.read_csv("../Datasets/Credit Card Defaulter Prediction.csv")
data.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default
0,1,20000,F,University,Married,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,Y
1,2,120000,F,University,Single,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,Y
2,3,90000,F,University,Single,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,N
3,4,50000,F,University,Married,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,N
4,5,50000,M,University,Married,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,N

## Encoding the Features

In [4]:
encoder = LabelEncoder()
for i in data.columns:
    data[i] = encoder.fit_transform(data[i])
data

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default
0,0,2,0,4,1,3,4,4,1,1,...,377,384,414,0,494,0,0,0,0,1
1,1,12,0,4,3,5,1,4,2,2,...,2344,2452,2402,0,699,885,946,0,1797,1
2,2,9,0,4,3,13,2,2,2,2,...,6135,6365,6480,1211,1185,885,946,949,3576,0
3,3,5,0,4,1,16,2,2,2,2,...,10118,10391,10482,1674,1674,1079,1043,1018,928,0
4,4,5,1,4,1,36,1,2,1,2,...,8476,7794,7708,1674,7301,5346,4841,647,630,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29995,22,1,2,1,18,2,2,2,2,...,16933,11087,6601,5201,6732,3737,2574,3576,928,0
29996,29996,15,1,2,3,22,1,1,1,1,...,4475,3143,414,1520,2854,5125,117,0,0,0
29997,29997,3,1,4,3,16,6,5,4,1,...,8460,8473,7828,0,0,6573,3249,1795,2582,1
29998,29998,8,1,2,1,20,3,1,2,2,...,14106,5519,13293,7762,2775,1058,1771,6552,1638,1
29999,29999,5,1,4,1,25,2,2,2,2,...,11697,11238,6419,1748,1475,1298,946,949,928,1

## Splitting into X & Y

In [5]:
X = data.drop(columns='default ')
Y = data['default ']
oversampler = RandomOverSampler(random_state=42)
over_sampled_data_X, over_sampled_data_Y = oversampler.fit_resample(X,Y)

# Splitting into testing and training

In [6]:
x_train,x_test,y_train,y_test = train_test_split(over_sampled_data_X , over_sampled_data_Y,test_size=0.2)

## Loading the model

In [7]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

## Predictions

In [8]:
y_pred = model.predict(x_test)

## Checking Errors

In [9]:
MAE  = mean_absolute_error(y_test,y_pred)
print(f" Error is :: {MAE}")

 Error is :: 0.41926303778512075