# Importing Various Libraries

In [101]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder,StandardScaler

# Loading the dataset

In [102]:
data = pd.read_csv("../Datasets/Credit Card Defaulter Prediction.csv")
data.head()

   ID  LIMIT_BAL SEX   EDUCATION  ... PAY_AMT4  PAY_AMT5  PAY_AMT6  default
0   1      20000   F  University  ...        0         0         0         Y
1   2     120000   F  University  ...     1000         0      2000         Y
2   3      90000   F  University  ...     1000      1000      5000         N
3   4      50000   F  University  ...     1100      1069      1000         N
4   5      50000   M  University  ...     9000       689       679         N

[5 rows x 25 columns]

# Label Encoding and Splitting into X & Y

In [ ]:
encoder = LabelEncoder()
for i in data.columns:
    data[i] = encoder.fit_transform(data[i])

from sklearn.preprocessing import StandardScaler

X = data.drop(columns=['default '])
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X = pd.DataFrame(X_scaled, columns=X.columns)
Y = data['default ']
data

          ID  LIMIT_BAL  SEX  EDUCATION  ...  PAY_AMT4  PAY_AMT5  PAY_AMT6  default
0          0          2    0          4  ...         0         0         0         1
1          1         12    0          4  ...       946         0      1797         1
2          2          9    0          4  ...       946       949      3576         0
3          3          5    0          4  ...      1043      1018       928         0
4          4          5    1          4  ...      4841       647       630         0
...      ...        ...  ...        ...  ...       ...       ...       ...       ...
29995  29995         22    1          2  ...      2574      3576       928         0
29996  29996         15    1          2  ...       117         0         0         0
29997  29997          3    1          4  ...      3249      1795      2582         1
29998  29998          8    1          2  ...      1771      6552      1638         1
29999  29999          5    1          4  ...       946       949       928         1

[30000 rows x 25 columns]

# Splitting for Training and Testing

In [104]:
x_train,x_test,y_train,y_test= train_test_split(X,Y,test_size=0.2, random_state=42)

# Loading the Model

In [105]:
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

# Predictions

In [106]:
y_pred = model.predict(x_test)

# Accuracy

In [107]:
accuracy = accuracy_score(y_test, y_pred)
print(f" Accuracy is :: {accuracy}")

 Accuracy is :: 0.8063333333333333