# Importing Required Libraries

In [48]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.metrics import accuracy_score, mean_squared_error

# Loading the dataset

In [49]:
data = pd.read_csv("../Datasets/kc_house_data.csv")
data.head()

           id             date     price  ...     long  sqft_living15  sqft_lot15
0  7129300520  20141013T000000  221900.0  ... -122.257           1340        5650
1  6414100192  20141209T000000  538000.0  ... -122.319           1690        7639
2  5631500400  20150225T000000  180000.0  ... -122.233           2720        8062
3  2487200875  20141209T000000  604000.0  ... -122.393           1360        5000
4  1954400510  20150218T000000  510000.0  ... -122.045           1800        7503

[5 rows x 21 columns]

# Encoding the Strings

In [50]:
encoder = LabelEncoder()
for i in data.columns:
    data[i] = encoder.fit_transform(data[i])
data

          id  date  price  bedrooms  ...   lat  long  sqft_living15  sqft_lot15
0      15339   164    349         3  ...  2398   223            109        2164
1      14466   220   2091         3  ...  4478   161            208        3470
2      13503   290    180         2  ...  4647   247            491        3804
3       6371   220   2373         4  ...  2492    87            116        1748
4       4955   283   1967         3  ...  3439   435            235        3357
...      ...   ...    ...       ...  ...   ...   ...            ...         ...
21608    574    19   1172         3  ...  4262   134            170         337
21609  14564   288   1399         4  ...  2393   118            243        3129
21610   3621    52   1408         2  ...  3223   181             40         547
21611    629   252   1399         3  ...  2629   411            131         185
21612   3622   166    958         2  ...  3220   181             40         242

[21613 rows x 21 columns]

# Standardizing the data

In [51]:
# scaler = StandardScaler()
# X = data.drop(columns=['price'])
# X_scaled = scaler.fit_transform(X)

# X = pd.DataFrame(X_scaled, columns=X.columns)
# Y = data['price']
# data

# Splitting into X & Y

In [52]:
X = data.drop(columns = ['price'])
Y = data['price']

# Splitting into training and Testing data

In [53]:
x_train,x_test,y_train,y_test= train_test_split(X,Y,test_size = 0.2, random_state = 42)

# Loading the model

In [54]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

# Making Predictions

In [55]:
y_pred = model.predict(x_test)

# Calculating Mean Squared Error

In [56]:
MSE = mean_squared_error(y_test,y_pred)
print(f" Mean Squared Error is :: {MSE}")

 Mean Squared Error is :: 241333.98983336258