# Importing required Libraries

In [45]:
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

# Loading the dataset

In [46]:
data = pd.read_csv("../Datasets/loan_data.csv",encoding = 'latin-1')
data

,Text,Income,Credit_Score,Loan_Amount,DTI_Ratio,Employment_Status,Approval
0,I need a loan to pay for an international vaca...,26556,581,8314,79.26,employed,Rejected
1,I want to make home improvements like installi...,197392,389,111604,22.14,employed,Rejected
2,"I need a loan for home renovation, including a...",44561,523,34118,45.44,employed,Rejected
3,I need funds to buy new furniture and applianc...,190363,729,118757,10.22,unemployed,Rejected
4,I need a loan to start a small business.,61853,732,19210,44.13,employed,Approved
...,...,...,...,...,...,...,...
23995,I need funds to pay for my daughter's college ...,195242,817,16403,24.32,employed,Approved
23996,I need financial assistance to launch my own Y...,150246,729,101572,9.97,employed,Rejected
23997,I need money to open a small bookstore and cafÃ©.,64571,650,30533,57.35,employed,Rejected
23998,I want to buy a car for my rideshare business ...,115825,418,89837,10.37,unemployed,Rejected
23999,I need financial help to cover maternity and d...,180440,769,15259,15.06,employed,Approved

# Encoding

In [47]:
encoder = LabelEncoder()
cv = CountVectorizer()
X = cv.fit_transform(data['Text'])  # sparse matrix
X_df = pd.DataFrame(X.toarray(), columns=cv.get_feature_names_out())
data = pd.concat([data.drop('Text', axis=1), X_df], axis=1)
data['Employment_Status'] = encoder.fit_transform(data['Employment_Status'])
data['Approval'] = encoder.fit_transform(data['Approval'])

data

,Income,Credit_Score,Loan_Amount,DTI_Ratio,Employment_Status,Approval,abroad,accident,adoption,advancement,...,want,water,website,wedding,with,woodworking,work,written,years,youtube
0,26556,581,8314,79.26,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1,197392,389,111604,22.14,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,44561,523,34118,45.44,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,190363,729,118757,10.22,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,61853,732,19210,44.13,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23995,195242,817,16403,24.32,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23996,150246,729,101572,9.97,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
23997,64571,650,30533,57.35,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23998,115825,418,89837,10.37,1,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
23999,180440,769,15259,15.06,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# Splitting into X & Y

In [48]:
X = data.drop(columns=['Approval'],axis = 1)
Y = data['Approval']

# Splitting into training and testing

In [49]:
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size =0.2 , random_state= 42)

# Loading the model

In [50]:
model = LogisticRegression(max_iter = 1000)
model.fit(X_train,y_train)

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

# Making predictions

In [51]:
y_prediction= model.predict(X_test)

# Checking Accuracy

In [52]:
accuracy = accuracy_score(y_test,y_prediction)
print(f" Accuracy is :: {accuracy}")

 Accuracy is :: 0.92625