# Importing required Libraries

In [181]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,mean_absolute_error
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.tree import DecisionTreeClassifier
import warnings
warnings.filterwarnings("ignore")
from collections import Counter

# Loading the dataset

In [182]:
data = pd.read_csv("../Datasets/cybersecurity_intrusion_data.csv")
data.head()

  session_id  network_packet_size  ... unusual_time_access  attack_detected
0  SID_00001                  599  ...                   0                1
1  SID_00002                  472  ...                   0                0
2  SID_00003                  629  ...                   0                1
3  SID_00004                  804  ...                   0                1
4  SID_00005                  453  ...                   0                0

[5 rows x 11 columns]

# Encoding the labels

In [183]:
encoder = LabelEncoder()
for i in data.columns:
    data[i] = encoder.fit_transform(data[i])

data

      session_id  network_packet_size  ...  unusual_time_access  attack_detected
0              0                  530  ...                    0                1
1              1                  403  ...                    0                0
2              2                  560  ...                    0                1
3              3                  735  ...                    0                1
4              4                  384  ...                    0                0
...          ...                  ...  ...                  ...              ...
9532        9532                  125  ...                    0                1
9533        9533                  311  ...                    0                0
9534        9534                  595  ...                    0                0
9535        9535                  337  ...                    1                0
9536        9536                  271  ...                    1                1

[9537 rows x 11 columns]

# Counting missing values

In [184]:
# missing_counts = data.isnull().sum()
# print(missing_counts[missing_counts > 0])  # Only print columns with missing values

# Plotting Missing Values

In [185]:

# missing_counts = missing_counts[missing_counts > 0]
# missing_counts.sort_values(ascending=False).plot(kind='bar', figsize=(10,5), color='salmon')
# plt.title("Missing Values Count per Column")
# plt.xlabel("Columns")
# plt.ylabel("Number of Missing Values")
# plt.grid(True)
# plt.show()

# Filling missing values

In [186]:
data['encryption_used'] = data['encryption_used'].fillna(data['encryption_used'].median())

# Separating X & Y

In [187]:
X = data.drop(columns=['attack_detected'])
Y = data['attack_detected']

# Scaling

# Splitting into training and testing

In [188]:
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size = 0.2,random_state =10)

In [189]:

scaler = StandardScaler()
x_train = scaler.fit_transform(X_train)
x_test = scaler.transform(X_test)

# Loading the model

In [190]:
model = DecisionTreeClassifier(max_depth = 6, min_samples_split = 10,random_state =10)
model.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=6, min_samples_split=10, random_state=10)

# Predictions and Accuracty

In [191]:
predictions = model.predict(X_test)
accuracy = accuracy_score(y_test,predictions)
print(f" Accuracy is :: {accuracy}")

 Accuracy is :: 0.8957023060796646