# Importing required Libraries

In [20]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,mean_absolute_error
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.tree import DecisionTreeClassifier
import warnings
warnings.filterwarnings("ignore")
from collections import Counter

# Loading the dataset

In [21]:
data = pd.read_csv("../Datasets/voice.csv")
data.head()

,meanfreq,sd,median,Q25,Q75,IQR,skew,kurt,sp.ent,sfm,...,centroid,meanfun,minfun,maxfun,meandom,mindom,maxdom,dfrange,modindx,label
0,0.059781,0.064241,0.032027,0.015071,0.090193,0.075122,12.863462,274.402906,0.893369,0.491918,...,0.059781,0.084279,0.015702,0.275862,0.007812,0.007812,0.007812,0.000000,0.000000,male
1,0.066009,0.067310,0.040229,0.019414,0.092666,0.073252,22.423285,634.613855,0.892193,0.513724,...,0.066009,0.107937,0.015826,0.250000,0.009014,0.007812,0.054688,0.046875,0.052632,male
2,0.077316,0.083829,0.036718,0.008701,0.131908,0.123207,30.757155,1024.927705,0.846389,0.478905,...,0.077316,0.098706,0.015656,0.271186,0.007990,0.007812,0.015625,0.007812,0.046512,male
3,0.151228,0.072111,0.158011,0.096582,0.207955,0.111374,1.232831,4.177296,0.963322,0.727232,...,0.151228,0.088965,0.017798,0.250000,0.201497,0.007812,0.562500,0.554688,0.247119,male
4,0.135120,0.079146,0.124656,0.078720,0.206045,0.127325,1.101174,4.333713,0.971955,0.783568,...,0.135120,0.106398,0.016931,0.266667,0.712812,0.007812,5.484375,5.476562,0.208274,male

# Encoding the labels

In [22]:
encoder = LabelEncoder()
for i in data.columns:
    data[i] = encoder.fit_transform(data[i])

data

,meanfreq,sd,median,Q25,Q75,IQR,skew,kurt,sp.ent,sfm,...,centroid,meanfun,minfun,maxfun,meandom,mindom,maxdom,dfrange,modindx,label
0,3,2243,6,35,3,1305,3063,3059,1379,2151,...,3,66,44,117,0,1,0,0,0,1
1,5,2392,9,45,4,1292,3090,3100,1347,2272,...,5,485,52,95,5,1,3,7,63,1
2,8,2964,8,24,11,2616,3155,3155,516,2072,...,8,267,41,113,2,1,1,1,36,1
3,464,2580,562,485,736,2165,258,288,3018,2990,...,464,95,166,95,281,1,67,79,2481,1
4,248,2826,214,329,647,2714,139,327,3136,3135,...,248,447,119,109,1369,1,624,665,2280,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3163,206,2990,520,184,468,2891,965,1104,3004,3092,...,206,2796,866,105,1612,1,485,522,1864,0
3164,102,3093,41,148,609,2941,13,5,2971,2938,...,102,2925,535,117,1760,11,398,432,2618,0
3165,338,3146,1301,100,1478,3052,1128,1093,2783,2794,...,338,3139,579,117,890,1,301,322,2183,0
3166,355,3109,1353,156,1267,3020,697,701,2839,2860,...,355,2486,536,95,1520,1,386,425,2735,0
3167,848,3132,1268,291,2613,3036,881,831,2621,2639,...,848,2864,817,113,339,1,66,77,2828,0

# Counting missing values

In [23]:
missing_counts = data.isnull().sum()
print(missing_counts[missing_counts > 0])  # Only print columns with missing values

Series([], dtype: int64)

# Plotting Missing Values

In [24]:

# missing_counts = missing_counts[missing_counts > 0]
# missing_counts.sort_values(ascending=False).plot(kind='bar', figsize=(10,5), color='salmon')
# plt.title("Missing Values Count per Column")
# plt.xlabel("Columns")
# plt.ylabel("Number of Missing Values")
# plt.grid(True)
# plt.show()

# Filling missing values

In [25]:
# data['encryption_used'] = data['encryption_used'].fillna(data['encryption_used'].median())

# Separating X & Y

In [26]:
X = data.drop(columns=['label'])
Y = data['label']

# Scaling

# Splitting into training and testing

In [27]:
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size = 0.2,random_state =10)

In [ ]:

# scaler = StandardScaler()
# x_train = scaler.fit_transform(X_train)
# x_test = scaler.transform(X_test)

# Loading the model

In [29]:
model = DecisionTreeClassifier(max_depth = 6, min_samples_split = 10,random_state =10)
model.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=6, min_samples_split=10, random_state=10)

# Predictions and Accuracy

In [30]:
predictions = model.predict(X_test)
accuracy = accuracy_score(y_test,predictions)
print(f" Accuracy is :: {accuracy}")

 Accuracy is :: 0.9605678233438486