# Importing required Libraries

In [82]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,mean_absolute_error
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.tree import DecisionTreeRegressor,DecisionTreeClassifier
import warnings
warnings.filterwarnings("ignore")
from collections import Counter

# Loading the dataset

In [83]:
data = pd.read_csv("../Datasets/bike_sales_100k.csv")
data.head()

,Sale_ID,Date,Customer_ID,Bike_Model,Price,Quantity,Store_Location,Salesperson_ID,Payment_Method,Customer_Age,Customer_Gender
0,1,11-07-2022,9390,Cruiser,318.32,1,Philadelphia,589,Apple Pay,70,Female
1,2,03-05-2024,3374,Hybrid Bike,3093.47,4,Chicago,390,Apple Pay,37,Male
2,3,01-09-2022,2689,Folding Bike,4247.99,3,San Antonio,338,PayPal,59,Female
3,4,28-09-2022,3797,Mountain Bike,1722.01,3,San Antonio,352,Apple Pay,19,Male
4,5,05-01-2021,1633,BMX,3941.44,3,Philadelphia,580,PayPal,67,Female

# Encoding the labels

In [84]:
encoder = LabelEncoder()
for i in data.columns:
    data[i] = encoder.fit_transform(data[i])

data

,Sale_ID,Date,Customer_ID,Bike_Model,Price,Quantity,Store_Location,Salesperson_ID,Payment_Method,Customer_Age,Customer_Gender
0,0,602,8390,1,2247,0,4,489,0,52,0
1,1,138,2374,4,54508,3,0,290,0,19,1
2,2,42,1689,3,76310,2,6,238,5,41,0
3,3,1576,2797,5,28631,2,6,252,0,1,1
4,4,229,633,0,70632,2,4,480,5,49,0
...,...,...,...,...,...,...,...,...,...,...,...
99995,99995,882,6584,4,54411,1,4,16,5,42,0
99996,99996,512,8076,6,16094,1,5,53,2,49,0
99997,99997,746,2944,3,48639,3,5,24,4,19,0
99998,99998,740,2334,4,76632,3,4,510,2,39,1
99999,99999,458,2090,1,43919,0,6,466,3,23,0

# Counting missing values

In [85]:
# missing_counts = data.isnull().sum()
# print(missing_counts[missing_counts > 0])  # Only print columns with missing values

# Plotting Missing Values

In [86]:

# missing_counts = missing_counts[missing_counts > 0]
# missing_counts.sort_values(ascending=False).plot(kind='bar', figsize=(10,5), color='salmon')
# plt.title("Missing Values Count per Column")
# plt.xlabel("Columns")
# plt.ylabel("Number of Missing Values")
# plt.grid(True)
# plt.show()

# Filling missing values

In [87]:
# data['encryption_used'] = data['encryption_used'].fillna(data['encryption_used'].median())

# Scaling

In [88]:

scaler = StandardScaler()
data['Price'] = scaler.fit_transform(data[['Price']])

# Separating X & Y

In [89]:
X = data.drop(columns=['Customer_Gender','Sale_ID','Customer_ID','Date','Salesperson_ID'])
Y = data['Customer_Gender']

# Splitting into training and testing

In [90]:
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size = 0.2,random_state =10)

# Loading the model

In [91]:
model = DecisionTreeClassifier(max_depth=10)
model.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=10)

# Predictions and Error

In [92]:
predictions = model.predict(X_test)
#MAR = mean_absolute_error(y_test,predictions)
accuracy = accuracy_score(y_test,predictions)
#print(f" Error is :: {MAR}")
print(f" Accuracy is :: {accuracy}")

 Accuracy is :: 0.5071

# Plotting

In [93]:
# sns.countplot(x = )